fixes about 503 blocks, removed deprecated libs, general updates
gippy/kickstart-location-to-id pull request #1
Opened 2021-05-17 15:45 UTC by OlehVeselov92

- fixed issue with 503 blocks instead of normal response with JSON info;
- Updated SDK to 1.2.0 (+ General fixes regarding new version);
- removed usage of deprecated "request-promise" library (using Apify.utils.requestAsBrowser() instead);
- implemented usage of proxy (auto configurations) by default;

2021-05-17 20:12 UTC, pocesar requested changes

2021-05-17 20:12 UTC, pocesar commented on apify_storage/key_value_stores/default/OUTPUT.json
>        "state": "Prague",
delete the file after setting the folder to gitignore

2021-05-17 20:12 UTC, pocesar commented on main.js
> +                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
I think that using got-scraping internally by requestAsBrowser, passing the headers manually isn't the best way. only `Accept: 'application/json'` should remain

2021-05-17 20:12 UTC, pocesar commented on main.js
>      do {
this loop could become a CheerioCrawler / BasicCrawler instance, the code is very much optimistic that things will just work (no blocks, proper json payload received, 200 http code, etc)

2021-05-17 20:45 UTC, metalwarrior665 commented
Wow, "apify": "^0.9.15", that is the record :D

2021-05-18 19:12 UTC, pocesar requested changes
thanks man! almost there

2021-05-18 19:12 UTC, pocesar commented on main.js
> +            if (!response.locations) log.error('Response does not contain locations. Try again.');
throw here for retrying

2021-05-18 19:12 UTC, pocesar commented on main.js
> +                proxyUrl: proxyConfiguration.newUrl(),
`proxyConfiguration.newUrl(session.id)`

2021-05-18 19:12 UTC, pocesar commented on main.js
> +    if (!input) log.error('Can not get input');
throw instead of log

2021-05-18 19:12 UTC, pocesar commented on main.js
> +    if (!query || typeof query !== 'string') log.error('Query loaded from INPUT is empty or not a string.');
same

2021-05-18 20:36 UTC, pocesar approved these changes

2021-05-18 20:36 UTC, pocesar commented
I'm going to run here in a bit to see how is everything and will release in a bit

2021-05-18 22:11 UTC, merged